name: .NET Build, Pack, and Push

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Setup version
      run: |
        sudo apt install jq
        VERSION=`jq ".info.version" openapi.json | tr -d \"`
        VERSION_NEW=`echo $VERSION | sed -e "s/X/$GITHUB_RUN_NUMBER/"`
        sed -i -e "s/$VERSION/$VERSION_NEW/" openapi.json
        echo "BUILD_VERSION=`echo $VERSION_NEW`" >> $GITHUB_ENV

    - name: Adjust NuGet config credentials
      run: |
        rm -f ./nuget.config
        mv nuget.ci.config nuget.config
        echo $(sed -e "s/\${USER}/${{ secrets.PACKAGE_USER }}/" -e "s@\${PAT}@${{ secrets.PACKAGE_PASSWORD }}@" nuget.config) > nuget.config

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration ${{ secrets.PACKAGE_CONFIG }} /p:VersionPrefix=${{ env.BUILD_VERSION }}

    - name: Pack
      run: dotnet pack --configuration ${{ secrets.PACKAGE_CONFIG }} --no-build /p:Version=${{ env.BUILD_VERSION }}

    - name: Push
      run: dotnet nuget push **/*.nupkg --source "github" --skip-duplicate --api-key ${{ secrets.PACKAGE_PASSWORD }}
